en/docs/11.md
=> Fix module loading in Chainer section

en/docs/appendix2.md, en/mkdocs.yml, ja/docs/appendix2.md, ja/mkdocs.yml
HPCI向けアクセスサーバ導入に伴い、利用手引書を修正しました。
- Appendix2 を追加
- mkdocs.yml にAppendix2 を追加
=> Create appendix2 for HPCI

en/mkdocs.yml, ja/mkdocs.yml
This pull request is ready to be merged.
=> Enable: Japanese live search

en/docs/06.md, ja/docs/06.md, ja/docs/07.md
=> reconstruct section 6 (Python)

en/docs/04.md, ja/docs/04.md
Add documents for BeeOND advanced options.
- Configure # of metadata servers and storage servers
- Configure file striping
=> Add BeeGFS advanced option

en/docs/appendix1.md, ja/docs/appendix1.md
CUDA 対応 Open MPI の configure オプションを修正しましたので、
ご確認の上、マージをお願いします。
=> Fix configure option for openmpi with CUDA in appendix1.md

ja/docs/abci-cloudstorage/usage.md
=> mod abci-cloudstorage/usage.md

en/docs/abci-cloudstorage/acl.md, ja/docs/abci-cloudstorage/acl.md
=> Remove old lines in abci-cloudstorage/acl.md

en/docs/01.md
typo で同じ行を書いてしまっているようでしたので、その修正です。
日本語版と比較しても、この行は余分のようです。
=> Remove a duplicate line

en/docs/01.md, en/docs/08.md, ja/docs/01.md, ja/docs/08.md
=> mod 1.3 and 8.

en/docs/01.md, ja/docs/01.md
Scality S3 Connector のバージョンをメンテナンスでアップデートされたバージョンに合わせました。
=> Update S3C version number

en/docs/appendix1.md, ja/docs/appendix1.md
Remove "Deep Learning Framework" and "Big Data" subsections in appendix1
=> Remove some subsections in appendix1

en/docs/03.md, en/docs/09.md, en/docs/apps/others.md, en/docs/apps/tensorflow.md, en/docs/ngc.md, en/docs/tips/jupyter-notebook.md, en/docs/tips/remote-desktop.md, en/docs/tips/sregistry-cli.md, ja/docs/03.md, ja/docs/09.md, ja/docs/apps/chainer.md, ja/docs/apps/mxnet.md, ja/docs/apps/others.md, ja/docs/apps/pytorch.md, ja/docs/apps/tensorflow-keras.md, ja/docs/apps/tensorflow.md, ja/docs/ngc.md, ja/docs/tips/jupyter-notebook.md, ja/docs/tips/remote-desktop.md, ja/docs/tips/sregistry-cli.md
qrsh の例に `-l h_rt=1:00:00` を付加しました。
=> Update qrsh examples

en/docs/apps/chainer.md, en/docs/apps/index.md, en/docs/apps/mxnet.md, en/docs/apps/pytorch.md, en/docs/apps/tensorflow-keras.md
ja/docs/apps/以下にある各種アプリケーションのページの英語版を用意しました。
=> 各種アプリケーションページの英語版

en/docs/appendix1.md, ja/docs/appendix1.md
* Add GDRCopy
* Add UCX 1.7 (for 7.4.0)
* Fix UCX 1.7 (for 4.8.5) w/o CUDA
=> Add GDRcopy configuration and UCX 1.7 for GCC 7.4.0 in Appendix1

en/docs/09.md, ja/docs/09.md
The English documentation was missing the example for using Singularity with MPI applications.
cc @boom10899
=> Add example for using Singularity with MPI to en/

en/docs/faq.md, ja/docs/faq.md
=> Add access to Grafana

en/docs/01.md, ja/docs/01.md
3箇所修正しています。
* Optane SSD の製品情報へのリンク
* typo (IntelR => Intel)
* Optane memory => Optane SSD (英語版のみ。日本語はすでに Optane SSD)
=> Fix SSD / Optane SSD info

en/docs/faq.md, ja/docs/faq.md
FAQに、バッチジョブで singularity pull でのイメージファイル作成するときに、
失敗する場合の回避策を追加しました。
=> Fj20200730 00

en/docs/01.md, en/docs/09.md, en/docs/faq.md, en/docs/ngc.md, en/docs/system-updates.md, en/docs/tips/dl-amazon-ecr.md, en/docs/tips/jupyter-notebook.md, ja/docs/01.md, ja/docs/09.md, ja/docs/faq.md, ja/docs/ngc.md, ja/docs/system-updates.md, ja/docs/tips/dl-amazon-ecr.md, ja/docs/tips/jupyter-notebook.md
=> Use "SingularityPRO" instead of "Singularity PRO" or "Singularity Pro" consistently

en/docs/abci-cloudstorage/acl.md
=> Correct names of agreements

en/docs/apps/mxnet.md, en/docs/apps/pytorch.md, en/docs/apps/tensorflow-keras.md, en/docs/apps/tensorflow.md, ja/docs/apps/mxnet.md, ja/docs/apps/pytorch.md, ja/docs/apps/tensorflow-keras.md, ja/docs/apps/tensorflow.md
horovod のインストールが v0.20.0 から変更になったため、手順書を修正しました。
=> modify horovod install relation

en/docs/02.md, en/docs/04.md, ja/docs/02.md, ja/docs/04.md
#199 (グループディレクトリの案内) への対応です。 
少し見出しを修正しています。
ドキュメント内でそれらの id を指定して参照している箇所はありませんでした。
=> Add sentence about finding group directory path

en/docs/03.md, ja/docs/03.md
[#3016](https://my.redmine.jp/aist.rp-ith/issues/3016) の対応で、予約ノード利用時の注意点を追加しました。
=> Add reserved node note

en/docs/abci-singularity-endpoint.md, ja/docs/abci-singularity-endpoint.md
redmineチケット2243に関して、ABCI user guideの修正を行いました。
https://my.redmine.jp/aist.rp-ith/issues/2343
list_singularity_libraryコマンドに関する説明を追加しています。
=> mod abci-singularity-endpoint

en/docs/tips/spack.md, ja/docs/tips/spack.md
add description of packages.yaml
=> update spack description

en/docs/05.md, en/docs/08.md, en/docs/09.md, en/docs/10.md, ja/docs/05.md, ja/docs/08.md, ja/docs/09.md, ja/docs/10.md, ja/docs/apps/chainer.md, ja/docs/tips/remote-desktop.md
既にマージ済みですがdevel-202104ブランチを戸澤の方でもチェックしました。
いくつか気になる点がありましたので修正しプルリクエストを送ります。
**足りない文を追加**
実行例において、ES上でそのまま実行するとエラーになるものを修正しました。
* en/docs/05.md
* en/docs/08.md
* en/docs/09.md
* ja/docs/05.md
* ja/docs/08.md
* ja/docs/09.md
**pgi/20.4 モジュールにおけるPGI C++コンパイラー名**
pgi/20.4 で利用できるPGI C++コンパイラーのコマンドが `pgCC` となっていましたが、 `pgc++` が正しいと思われます。
pgCCコマンドはありませんでした。
* en/docs/10.md
* ja/docs/10.md
**誤植の修正**
誤植と思われる箇所を修正しました。
* ja/docs/apps/chainer.md
* ja/docs/tips/remote-desktop.md
=> Reviewed devel-202104 branch.

en/docs/01.md, en/docs/03.md
=> Too few columns in 2 lists.

en/docs/abci-datasets.md, ja/docs/abci-datasets.md
abci-application-ml@aist.go.jp -> M-abci-datasets-ml@aist.go.jp
=> Change ML for datasets

en/docs/apps/chainer.md, en/docs/apps/mxnet.md, en/docs/apps/pytorch.md, en/docs/apps/tensorflow-keras.md, en/docs/apps/tensorflow.md, ja/docs/apps/chainer.md, ja/docs/apps/mxnet.md, ja/docs/apps/pytorch.md, ja/docs/apps/tensorflow-keras.md, ja/docs/apps/tensorflow.md
* Tensorflow、Tensorflow-Keras、PyTorch、MXNetのGNU Modulesの構成を修正しました。
* 計算ノード(V)、計算ノード(A)環境でサンプルプログラムが動作することを確認済みです。
* Pythonのバージョンを3.8系にあげました。
* Horovodのバージョンを0.22.0にあげました。
* 文言を修正しました。
Chainerとその他のページについてはまだ確認できていません。
=> Fix the deep learning frameworks.

en/docs/apps/chainer.md, en/docs/apps/mxnet.md, en/docs/apps/pytorch.md, en/docs/apps/tensorflow-keras.md, en/docs/apps/tensorflow.md, ja/docs/apps/chainer.md, ja/docs/apps/mxnet.md, ja/docs/apps/others.md, ja/docs/apps/pytorch.md, ja/docs/apps/tensorflow-keras.md, ja/docs/apps/tensorflow.md
* TensorFlow-Kerasのページに、サンプルの実行以外はTensorFlowのページと同じものである旨の注釈を追加しました。
* サンプル実行のためのHorovodのバージョンが古いままでしたので、これを修正しました。
=> Added the note about Keras.

en/docs/getting-started.md, en/docs/mpi.md, en/docs/system-updates.md, ja/docs/getting-started.md, ja/docs/mpi.md, ja/docs/system-updates.md
7/2-6の保守作業時にアップデートしたSingularityPROの情報を記載しました。(system-updates.md)
また、運用時に判明した修正箇所について併せて修正を行いました。(getting-started.md , mpi.md)
=> mod system-updates.md ,getting-started.md and fix mpi.md

en/docs/containers.md, ja/docs/containers.md
redmineチケット#2653 に関して、singularity の定義ファイル例を記載しました。
ご確認のほど、よろしくお願いします。
https://my.redmine.jp/aist.rp-ith/issues/2653
=> mod containers.md

en/docs/abci-cloudstorage/s3fs-usage.md, en/mkdocs.yml, ja/docs/abci-cloudstorage/s3fs-usage.md, ja/docs/abci-cloudstorage/usage.md, ja/mkdocs.yml
Fixed a code block in the usage.md(ja) file.
=> Added the s3fs-fuse usage.

en/docs/system-updates.md, ja/docs/system-updates.md
redmineチケット4218でご依頼のありました、「システム更新履歴」の修正を実施しました。
ご確認のほどよろしくお願いします。
https://my.redmine.jp/aist.rp-ith/issues/4218
=> mod system-updates.md

en/docs/storage.md, ja/docs/storage.md
Redmineチケット [#3115](https://my.redmine.jp/aist.rp-ith/issues/3115) に関する、show_scratchコマンドの記載を追加しました。
ご確認よろしくお願いいたします。
=> Fj20220120 01

en/docs/faq.md, ja/docs/faq.md
新年度に向けて、データ移行に関する記述を削除しました。
年度明けの merge を想定しています。
=> Detail about the data migration is no longer documented in FY2022.

en/mkdocs.yml, en/overrides/main.html, ja/mkdocs.yml, ja/overrides/main.html, portal/en/mkdocs.yml, portal/en/overrides/main.html, portal/ja/mkdocs.yml, portal/ja/overrides/main.html
ABCIユーザーガイドおよび、利用者ポータルガイドのGoogle AnalyticsをPlausible Analytics (analytics.abci.ai) に変更するPull Requestです。
headタグへのスニペットの埋め込みはmkdocs-materialの[テーマの変更方法](https://squidfunk.github.io/mkdocs-material/customization/#overriding-blocks)を参考に行っています。
=> Use Plausible Analytics

en/docs/abci-cloudstorage.md, en/docs/appendix/using-abci-with-hpci.md, en/docs/getting-started.md, en/docs/tips/jupyter-notebook.md, ja/docs/abci-cloudstorage.md, ja/docs/appendix/using-abci-with-hpci.md, ja/docs/getting-started.md, ja/docs/tips/jupyter-notebook.md
コードブロックの書式がおかしいものを修正しました。
また、英語版においてtypoをいくつか修正しています。
=> Fixed code block format

en/docs/containers.md, ja/docs/containers.md
坂部様に書いて頂いたドラフトをもとにプルリクエストを作成しました。
また、Singularity Proのバージョンを更新(3.7->3.9)しました。
=> Add intro regarding containers.

en/docs/getting-started.md, ja/docs/getting-started.md
redmineチケット4575でご依頼のありました、sshのversionをABCI利用の手引きへの追記を実施しました。ご確認のほどよろしくお願いします。
https://aist-rp-ith.cloud.redmine.jp/issues/4575
=> mod getting-started.md

portal/en/docs/index.md, portal/ja/docs/index.md
redmineチケット4575でご依頼のありました、推奨ブラウザの名前とversionをABCI利用者ポータルの利用の手引きに追記しました。ご確認のほどよろしくお願いします。
=> mod index.md of user portal

en/docs/system-updates.md, ja/docs/system-updates.md
redmineチケット4413でご依頼のありました、更新履歴に更新予定を記載しました。
ご確認のほどよろしくお願いします。
=> mod system-updates

en/docs/faq.md, ja/docs/faq.md
Singularity イメージ作成時のエラーメッセージ例を FAQ に追記しました。
ご確認のほどよろしくお願いいたします。
=> Add error message sample in faq.md

en/docs/gpu.md, en/docs/system-updates.md, ja/docs/gpu.md, ja/docs/system-updates.md
GPU Compute Modeを変更するジョブ実行オプションの修正を実施しました。ご確認のほどよろしくお願いいたします。
=> Fix GPU Compute Mode

en/docs/tips/sharp.md, en/mkdocs.yml, ja/docs/tips/sharp.md, ja/mkdocs.yml
[Redmine チケット4839](https://aist-rp-ith.cloud.redmine.jp/issues/4839)に関連して、SHARP-NCCLの利用方法をまとめました。
=> Added a chapter on how to use the SHARP-NCCL.

ja/docs/system-overview.md
インタラクティブノードの構成を示す表において、余計な文字列が混ざってしまっていたためこれを削除するプルリクエストです。
=> Removed unnecessary text.

en/docs/mpi.md, ja/docs/mpi.md
ABCIにおけるNVIDIA HPC-Xの利用方法を作成しました。
=> Using NVIDIA HPC-X

en/docs/job-execution.md, ja/docs/job-execution.md
チケット[#8370](https://aist-rp-ith.cloud.redmine.jp/issues/8370)にてご依頼のありましたqsub失敗時のエラーメッセージに関する利用手引きの修正です。
ご確認のほどよろしくお願いいたします。
=> add qsub error message

en/docs/getting-started.md, en/docs/system-updates.md, ja/docs/getting-started.md, ja/docs/system-updates.md
チケット#4888でご依頼いただいたshow_quotaコマンドでinode数を表示する修正に伴う利用手引きの修正、および#8733でご依頼いただいたシステム更新予定に関して記載いたしました。ご確認の程、何卒よろしくお願いいたします。
=> fix show_quota

en/docs/mpi.md, ja/docs/mpi.md
2023年度向けの修正プルリクエストです。
* NVIDIA HPC-Xのバージョンを修正
* Intel MPIのバージョンを修正
* OpenMPIの章を削除
=> Updated MPI

portal/en/docs/01.md, portal/en/docs/02.md, portal/en/docs/03.md, portal/ja/docs/01.md, portal/ja/docs/02.md, portal/ja/docs/03.md
redmine チケット 12396 ( https://aist-rp-ith.cloud.redmine.jp/issues/12396 ) でご依頼のありました。ポータルユーザガイドの修正を実施しました。ご確認のほどよろしくお願いします。
=> modified abci-user-manual for portal

en/docs/development-tools.md, ja/docs/development-tools.md
「開発ツール」のページを2023年度に対応するプルリクエストです。
* Intel oneAPIモジュールのバージョン更新。
* PGIの章を削除。
=> Updated Development Tools

en/docs/faq.md, ja/docs/faq.md
2023年度向けにFAQを修正しました。
* 「Q. 認証が必要なコンテナレジストリをSingularityで利用できない」
* ~~SingularityPROのユーザーガイドが現在公開されていない(sylabの認証が必要)ため、SingularityCEのユーザーガイドを設定しました。~~ 探し方が間違っていただけでした。
* 滝澤様よりSingularityPROのユーザーガイドのURLを教えて頂いたのでそちらに変更しました。
* 「Q. 複数の計算ノードを割り当て、それぞれの計算ノードで異なる処理をさせたい」
* openmpiモジュールを利用している箇所をhpcxに変更しました。
* 「Q. 計算ノード(A)と計算ノード(V)の違いが知りたい」
* CentOSとなっている箇所をRockyに変更しました。
=> Updated FAQ for FY2023.

en/docs/system-overview.md, en/docs/system-updates.md, ja/docs/system-overview.md, ja/docs/system-updates.md
BeeONDのバージョンに関して以下のページに情報を追記しました。
ご確認のほどよろしくお願いします。
・system-updates
・system-overview
=> mod system-overview and system-updates about BeeOND version

en/docs/apps/cuquantum.md, en/mkdocs.yml, ja/docs/apps/cuquantum.md, ja/mkdocs.yml
ABCIでcuQuantum Applianceを利用する方法追加するプルリクエストです。
=> Add cuQuantum Appliance

en/docs/faq.md, ja/docs/faq.md
以下のチケットでご依頼のありました、inode個数を削減するためのライブラリについてFAQに記載しました。
ご確認のほどよろしくお願いします。
https://aist-rp-ith.cloud.redmine.jp/issues/13815
=> mod faq about #13185

en/docs/containers.md, ja/docs/containers.md
[#17914](https://aist-rp-ith.cloud.redmine.jp/issues/17914) 利用手引きの修正を実施いたしました。ご確認のほどよろしくお願いします。
* fakeroot使用時のSINGULARITY_TMPDIR環境変数に関する説明の追加
=> modify containers.md abount fakeroot build

en/docs/system-overview.md, en/docs/system-updates.md, ja/docs/system-overview.md, ja/docs/system-updates.md
2023年12月のメンテナンス作業に伴う、利用手引きの修正となります。
・SingularityPROのバージョン変更
・rcloneの追加
=> mod system-overview and system-updates

en/docs/containers.md, en/docs/faq.md, ja/docs/containers.md, ja/docs/faq.md
2023年12月のメンテナンス作業において、SingularityPROのアップデート作業に伴う、利用手引きの修正となります。
* containers.md : SingularityPROのバージョンおよびUserGuideのリンクを修正
* faq.md : UserGuideのリンクを修正
=> mod containers and faq about singularitypro

en/docs/faq.md, ja/docs/faq.md
2023年度版 ABCI modules用のPull Requestです。
=> Added line for 2023 version.

en/docs/index.md, en/mkdocs.yml, ja/docs/index.md, ja/mkdocs.yml
以下のチケットでご依頼のありました、利用手引きの修正を実施しました。ご確認のほどよろしくお願いします。
https://aist-rp-ith.cloud.redmine.jp/issues/19216
=> Fj20240619 00

.github/workflows/pages.yml, Makefile
ABCI 3.0のドキュメント(v3ディレクトリ下)を公開するためのPull Requestです。
=> Publishing ABCI 3.0 document

v3/portal/root/mkdocs.yml
ABCI 3.0 Portal Guideのトップアクセス時(`/v3/portal/`)のリダイレクト先URLを修正するPull Requestです。
=> Fixed root redirect_maps
