aistabci/abci-docs

- en/docs/ngc.md
- ja/docs/ngc.md
サンプルスクリプトを wget で github から取得するようにしたのと、
元々 wget するようになっていたものも、タグを使ったURLに置き換えて少しわかりやすい(手打ちしやすい)URLにものにしています。
> Devel ngc updating examples

- en/docs/ngc.md
- ja/docs/ngc.md
ngc の tensorflow のコンテナイメージが更新されていましたので、それに合わせました。以前のイメージもダウンロード可能でした。
cnn_mnist.py の取りに行く先を v1.12.0 から v1.13.1 に変えました。
不具合があったわけではなく、イメージに埋まっている tensorflow のバージョンに合わせました。
> Updating ngc section

- en/docs/tips/spack.md
- ja/docs/tips/spack.md
GCC 7.4.0を使う場合、コンパイラのextra_rpathにGCC 7.4.0のライブラリを設定しないと、一部のソフトウェア（発生したのはOpenMPI  3.1.3 compiled with GCC 7.4.0）で実行時エラーになることを確認しました。
> Modify document bugs

- en/docs/index.md
- ja/docs/index.md
index.md の方に spack のエントリがないのに気がつきましたので、追加です。
mkdocs.yml の方にはエントリがあります。
> Add missing lines for Spack

- en/docs/09.md
- en/docs/faq.md
- ja/docs/09.md
- ja/docs/faq.md
Singularity PRO 3.5 の User Guide公開について、Sylabs社より了承が得られたのでURLを修正しました。
（修正前はSingularity 3.5のUser Guide参照にしていました）
また、Singuklarity 2.6も、Singularity PRO 3.5 と書き方を統一するため修正しています。
> Fj20200729 01

- en/docs/faq.md
基本的には pass => PATH の typo の修正ですが、setting の代わりに adding を使うなど少し表現変えました(settingで問題はなかったのですが)。
> Fix a typo in faq.md

- en/docs/02.md
- ja/docs/02.md
Windows 10 の吊るしのsshでProxCommandを使用する方法を追記しました。
> fix Windows 10 ProxyCommand instruction

- en/docs/system-updates.md
- ja/docs/system-updates.md
Scality S3 Connectorのアップデート (7.4.5.4 -> 7.4.6.3 ) を実施しましたので
利用手引きの「システム更新履歴」に追加しました。
> Update Scality S3 Connector version

- ja/docs/abci-singularity-endpoint.md
必要なくなった警告文の削除です。
英語版の remote-builder ブランチは別途作業しました。
> Remove the warning not necessary any more about the number of key pairs

- en/docs/abci-singularity-endpoint.md
今回のメンテナンスに伴って更新された singularity endpoint のページ 
(コミット c50ff6f、プルリクエスト #230 の一部) の英語版です。
singularity endpoint の英語版は master にまだマージしてなくて devel-202012
ブランチで取り込まれましたので、そちらの差分が盛り込まれなかったものと思います。
https://github.com/aistairc/abci-docs/pull/230/commits/be7c2afeb65cbdf0eeff420a37b430bb0ae96029#diff-18fd64d4ba8b530bb585def9a27abfe348466ef81b5ea28c5d34ad284612c910
この差分の英語版です。
> Remove old admonitions

- en/docs/faq.md
- ja/docs/faq.md
計算ノードの/tmpが足りず singularity build/pullがエラーになった場合の対処方法をFAQに追加しました。
> 計算ノードでsingularity build/pull実行時に容量不足でエラーになった場合の対処方法をFAQに追加

- en/docs/tips/ngc.md
- ja/docs/tips/ngc.md
* NVIDIA NGC で利用しているTensorFlowコンテナのバージョンを19.06から21.06に更新しました。計算ノード(A)、(V)で動作することを確認済みです。
* NGC のドキュメントへのリンクが古くなっていたため、これも更新しました。
> Bump up container version to 21.06

- en/docs/job-execution.md
- ja/docs/job-execution.md
Reservedサービスにおいて、予約IDを使えるのが誰か記述がないため、予約を行える管理者しか予約ジョブを投げられないように見えます。
そこで、予約IDは「予約時に指定したABCIグループに所属するABCIアカウント」が使える文言を追加しました。
> Added some text about who can use the reservation ID.

- en/docs/containers.md
- en/docs/development-tools.md
- en/docs/environment-modules.md
- en/docs/faq.md
- en/docs/tips/jupyter-notebook.md
- en/docs/tips/ngc.md
- en/docs/tips/spack.md
- ja/docs/containers.md
- ja/docs/development-tools.md
- ja/docs/environment-modules.md
- ja/docs/faq.md
- ja/docs/tips/jupyter-notebook.md
- ja/docs/tips/ngc.md
- ja/docs/tips/spack.md
提供を終了している機能、モジュールを使用している文章を修正しました。
faq.md中以下のエントリは内容が古いため削除しました。
* `Q. グループ領域が実サイズ以上に消費されてしまう`
* ブロックサイズは現状4KBで統一されており、この問題は発生しない。
* `Q. NGC CLIが実行できない`
* NGC CLIの最新(3.4.1)版ではエラーが発生しないことを確認した。
* `Q. Open MPIの新しいバージョンが使いたい`
* CUDA-aware OpenMPIは現在提供していない。
38ed8c1
* Intel Parallel Studio XEのモジュール名を更新しました。
* NVIDIA HPC SDKは提供していないため、「開発ツール」のページから削除しました。
> Correct old content

- en/docs/system-updates.md
- ja/docs/system-updates.md
来年度にサポート外とするモジュール(pgi、openmpi、fuse-sshfs)の追加と、サポート外のあとの利用について、システム更新予定に文章を追加しました。
> Modules that no longer supported.

- en/docs/environment-modules.md
- ja/docs/environment-modules.md
2023年度のモジュール構成に併せて、例で使用しているモジュールのバージョンを更新しました。
変更点:
* Rocky Linux 8をサポート開始したCUDA 11.7系を使用。
* cuDNNはCUDA 11.7系をサポート開始しているバージョンを使用。
* それ以外はABCIでサポートしている最小バージョンを使用。
* ログインしているノードを計算ノードからインタラクティブノードに変更。
> Updated Environment Modules

- en/docs/system-updates.md
- ja/docs/system-updates.md
製品名としては「Singularity Enterprise」が正しいと思われるので、名前を変更しました。
また、英語版に「Singularityエンドポイント」となっている箇所があったのでこれも修正しています。
> Corrected Singularity Enterprise name

- en/docs/mpi.md
- ja/docs/mpi.md
HPC-Xの章において、テーブルの列名が"MPI Version"となっています。
これだとMPIの仕様バージョンにみえるため"Open MPI Version"としました。
> Corrected a column name in the table.

- en/docs/tips/spack.md
- ja/docs/tips/spack.md
Spackの設定方法に関する修正です。ご確認のほどよろしくお願いいたします。
初めてSpackをインストールした際、`spack compiler find`を実行せずに`spack compiler list`を実行すると、以下のエラーが発生して`spack compiler find`の実行を求められます。
```
[username@es1 ~]$ spack compiler list
==> No compilers available. Run `spack compiler find` to autodetect compilers
```
> Fj20230421 00

- portal/root/mkdocs.yml
- portal/root/overrides/main.html
- root/mkdocs.yml
- root/overrides/main.html
root/mkdocs.yml設定ファイルからGoogle Analyticsの設定を削除する修正です。
修正後、makeでコンテンツを生成したのち、site/以下のhtmlファイルにGoogle Analyticsのタグ(UA-)が含まれないことを確認しました。
また、root、portal/root以下にPlausible Analyticsの設定を追加しました。
修正後、privacy-policy/index.html、404.htmlページにPlausible Analyticsのタグが設定されることを確認しました。
> Removed Google Analytics configuration.

- en/docs/abci-cloudstorage.md
- en/docs/abci-cloudstorage/cs-account.md
- en/docs/abci-cloudstorage/policy.md
- en/docs/getting-started.md
- en/docs/job-execution.md
- en/docs/storage.md
ABCI の「利用管理者」を "User Administrator(s)" に統一。
クラウドストレージの管理者は AWS に合わせて "Usage Manager" とする。
> Unified translation.

- en/docs/apps/mxnet.md
- en/docs/apps/pytorch.md
- ja/docs/apps/mxnet.md
- ja/docs/apps/pytorch.md
* PyTorchのインストールバージョンを2.0.1を指定するようにしました。
* [PyTorchのドキュメント](https://pytorch.org/get-started/previous-versions/#linux-and-windows-3)では、 `--index-url`オプションでリポジトリを指定していますが、この場合litパッケージが足りずインストールに失敗します。そのため、litパッケージなどの足りないパッケージはPyPIから取得できるよう`--extra-index-url`オプションに変更しました。
* PyTorch+Horovod、MXNet+Horovodインストール時にwheelパッケージをインストールするようにしました。
* PEP 517のビルドに対応していないHorovodでは、pip 23.1以降wheelパッケージがインストールされていない場合にビルドが失敗するためです。
* 参考: [Deprecate call to setup.py install when wheel is absent for source distributions without pyproject.toml](https://github.com/pypa/pip/issues/8559)
* TensorFlowの場合は、TensorFlowのインストール時にwheelパッケージが追加インストールされるためHorovodのビルドエラーは発生しません。
> Fixed PyTorch version

- en/docs/tips/sharp.md
- ja/docs/tips/sharp.md
「SHARPの利用」ページを更新するPull Requestです。
修正内容:
* `nccl-rdma-sharp-plugins/v2.5.x-4ccb98a` モジュールを追加しました。
* 内容を2024年度版に修正しました。
* OpenMPI、CUDA 11.0など提供していないモジュールを削除、変更しました。
> Updated the SHARP contents.

- portal/en/overrides/main.html
- portal/ja/overrides/main.html
- portal/root/mkdocs.yml
ABCI 2.0ポータルガイドのルート(`https://docs.abci.ai/portal/`)訪問時にABCI 3.0ポータルガイド日本語版(`https://docs.abci.ai/v3/portal/ja/`)へリダイレクトする修正Pull Requestです。
また、ABCI 2.0のドキュメントを参照した場合に、ページトップにABCI 3.0ポータルガイドを参照するようアナウンスを表示する修正も加えています。 こちら文言について修正があればご指摘ください。
> Redirect to ABCI 3.0 Portal Guide.
